# Generated by Django 2.0.7 on 2019-03-22 07:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('outline', models.CharField(default='', max_length=500, verbose_name='简介')),
                ('readCount', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('label', models.CharField(default='', max_length=100, verbose_name='标签')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=[], verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
        ),
    ]
