# Generated by Django 2.0.7 on 2019-03-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190326_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=500, verbose_name='评论内容')),
                ('rate', models.FloatField(default=3, verbose_name='评分')),
                ('likes', models.IntegerField(default=0, verbose_name='评论点赞次数')),
                ('dislikes', models.IntegerField(default=0, verbose_name='评论不喜欢次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_comments', to='article.Article')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
