# Generated by Django 2.0.7 on 2019-03-22 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='电话号码')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='用户名')),
                ('code', models.CharField(default='', max_length=50, unique=True, verbose_name='暗号')),
                ('token', models.CharField(max_length=255, null=True, unique=True, verbose_name='token')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
